---
- name: Configure a Login Banner on Cisco IOS
  hosts: cisco
  gather_facts: false
  vars_files:
    - banner_vars.yml
  tasks:
    - name: Configure a Login Banner on Cisco IOS
      cisco.ios.ios_banner:
        banner: "{{ banner_type }}"
        text: "{{ network_banner }}"
        state: present
